:bug: Fixes docs build error from Node's fs
`fs` from Node now requires a callback for the third parameter, which was missing from the docs Gulp build task file, causing the `gulp build-docs` process to break with the following error:

```
[15:59:18] Starting 'build-docs'...
Building Metadata
Copying examples
Copying LESS source
Building Semantic for docs
(node:72733) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
fs.js:113
      throw err;  // Forgot a callback but don't know where? Use NODE_DEBUG=fs
      ^

Error: ENOENT: no such file or directory, open '/Users/username/Development/HTML/docs/out/metadata.json'
ITs-MacBook-Pro-6:ksc-ui photoroom$ ./node_modules/gulp/bin/gulp.js build-docs
```

Adding a simple error callback (with optional console log for error reporting) **fixes this issue**. Running the docs build process now works.

Not sure if this has already been hashed out for the next release cycle.